language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run clean
  - npm run build

deploy:
  provider: s3
  skip_cleanup: true
  bucket: kaylalynjones.design
  region: us-east-1
  local_dir: dist
